#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-distr
Version  : 2.9.7
Release  : 44
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/distr_2.9.7.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/distr_2.9.7.tar.gz
Summary  : Object Oriented Implementation of Distributions
Group    : Development/Tools
License  : LGPL-3.0
Requires: R-distr-lib = %{version}-%{release}
Requires: R-sfsmisc
Requires: R-startupmsg
BuildRequires : R-sfsmisc
BuildRequires : R-startupmsg
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-distr package.
Group: Libraries

%description lib
lib components for the R-distr package.


%prep
%setup -q -n distr
pushd ..
cp -a distr buildavx2
popd
pushd ..
cp -a distr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736793233

%install
export SOURCE_DATE_EPOCH=1736793233
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/distr/ARITHMETICS
/usr/lib64/R/library/distr/CITATION
/usr/lib64/R/library/distr/DESCRIPTION
/usr/lib64/R/library/distr/INDEX
/usr/lib64/R/library/distr/MASKING
/usr/lib64/R/library/distr/Meta/Rd.rds
/usr/lib64/R/library/distr/Meta/demo.rds
/usr/lib64/R/library/distr/Meta/features.rds
/usr/lib64/R/library/distr/Meta/hsearch.rds
/usr/lib64/R/library/distr/Meta/links.rds
/usr/lib64/R/library/distr/Meta/nsInfo.rds
/usr/lib64/R/library/distr/Meta/package.rds
/usr/lib64/R/library/distr/Meta/vignette.rds
/usr/lib64/R/library/distr/NAMESPACE
/usr/lib64/R/library/distr/NEWS
/usr/lib64/R/library/distr/R/distr
/usr/lib64/R/library/distr/R/distr.rdb
/usr/lib64/R/library/distr/R/distr.rdx
/usr/lib64/R/library/distr/TOBEDONE
/usr/lib64/R/library/distr/demo/ComparisonFFTandRtoDPQ.R
/usr/lib64/R/library/distr/demo/ConvolutionNormalDistr.R
/usr/lib64/R/library/distr/demo/Expectation.R
/usr/lib64/R/library/distr/demo/NormApprox.R
/usr/lib64/R/library/distr/demo/StationaryRegressorDistr.R
/usr/lib64/R/library/distr/demo/destructive.R
/usr/lib64/R/library/distr/demo/nFoldConvolution.R
/usr/lib64/R/library/distr/demo/range.R
/usr/lib64/R/library/distr/doc/index.html
/usr/lib64/R/library/distr/doc/newDistributions-knitr.R
/usr/lib64/R/library/distr/doc/newDistributions-knitr.Rnw
/usr/lib64/R/library/distr/doc/newDistributions-knitr.pdf
/usr/lib64/R/library/distr/help/AnIndex
/usr/lib64/R/library/distr/help/aliases.rds
/usr/lib64/R/library/distr/help/distr.rdb
/usr/lib64/R/library/distr/help/distr.rdx
/usr/lib64/R/library/distr/help/paths.rds
/usr/lib64/R/library/distr/html/00Index.html
/usr/lib64/R/library/distr/html/R.css
/usr/lib64/R/library/distr/tests/Examples/distr-Ex.Rout.save
/usr/lib64/R/library/distr/tests/doSvUnit.R
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunMinimum.R
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunMinimum.save
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunOperatorsMethods.R
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunOperatorsMethods.save
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunQQPlot.R
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunQQPlot1.save
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunQQPlot2.save
/usr/lib64/R/library/distr/tests/unitTests/runit.dontrunQQPlot3.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/distr/libs/distr.so
/V4/usr/lib64/R/library/distr/libs/distr.so
/usr/lib64/R/library/distr/libs/distr.so
